export const api = {
  netSearch: "https://api.bochaai.com/v1/ai-search",
  getModels: "https://dashscope.aliyuncs.com/api/v1/deployments/models",
  chat: "/api/v1/chat",
  login: "/api/v1/user/login",
  register: "/api/v1/user/register",
  validate: "/api/v1/auth/validate",
  refresh: "/api/v1/auth/refresh",
  logout: "/api/v1/auth/logout",
  uploadAvatar: "/api/v1/avatar/upload",
  updateInfo: "/api/v1/user/updateInfo",
  updatePassword: "/api/v1/user/updatePassword",
  deleteAccount: "/api/v1/user/deleteAccount",
  getPublicKey: "/api/v1/encryption/getPublicKey",
  sendVerificationCode: "/api/v1/user/sendVerificationCode",
  verifyCode: "/api/v1/user/verifyCode",
  resetPassword: "/api/v1/user/resetPassword",
  textToSpeech: "/api/v1/tts/textToSpeech",
  getVoiceLists: "/api/v1/tts/getVoiceLists",
  getVoiceModels: "/api/v1/tts/getVoiceModels",
  getVoiceLists: "/api/v1/tts/getVoiceLists",
  asrRecognize: "/api/v1/asr/recognize",
  addFavorites: "/api/v1/favorites",
  getUserFavorites: "/api/v1/favorites/getUserFavorites",
  removeFavorite: "/api/v1/favorites/removeFavorite",
  getFavoriteDetail: "/api/v1/favorites/getFavoriteDetail",
  saveConversation: "/api/v1/conversations/save",
  getConversations: "/api/v1/conversations/list",
  deleteConversation: "/api/v1/conversations/delete",
  getConversationDetail: "/api/v1/conversations/details",
  uploadKnowledge: "/api/v1/knowledge/upload",
  getKnowledgeList: "/api/v1/knowledge/list",
  deleteKnowledge: "/api/v1/knowledge/delete",
  getKnowledgeDetail: "/api/v1/knowledge/detail",
  downloadKnowledge: "/api/v1/knowledge/download",
  setModelConfig: "/api/v1/user/setModelConfig",
  getModelConfig: "/api/v1/user/getModelConfig",
  getSystemRoles: "/api/v1/role/system",
  getUserRoles: "/api/v1/role/user",
  getSelectedRole: "/api/v1/role/selected",
  getRole: "/api/v1/role",
  createRole: "/api/v1/role/create",
  updateRole: "/api/v1/role/update",
  deleteRole: "/api/v1/role/delete",
  selectRole: "/api/v1/role/select",
  clearRole: "/api/v1/role/clear",
};

// 需要认证的API
export const authRequiredApis = [
  api.validate,
  api.updateInfo,
  api.updatePassword,
  api.deleteAccount,
  api.setModelConfig,
  api.getModelConfig,
];

export default { api, authRequiredApis };
